services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./backend/.env
    environment:
      - GOOGLE_API_KEY=AIzaSyB7wPF-hLbv2ZLHZBLXeqVvG18dFxDNFMU
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
