import json
import logging

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, Query
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.config import settings
from app.database import get_db
from app.models.analysis import AnalysisRun
from app.models.cluster import Cluster
from app.models.incident import Incident
from app.pipeline.orchestrator import PipelineOrchestrator
from app.schemas.common import APIResponse
from app.services.llm_service import LLMService

router = APIRouter()
logger = logging.getLogger(__name__)

_orchestrator = PipelineOrchestrator()
_llm_svc = LLMService()


@router.get(
    "/health",
    response_model=APIResponse[dict],
    summary="Check Gemini API connectivity",
)
def llm_health() -> APIResponse[dict]:
    available = _llm_svc.is_available()
    return APIResponse(
        data={
            "available": available,
            "model": "gemini-1.5-flash",
            "status": "ready" if available else (
                "unavailable — check GOOGLE_API_KEY in environment"
            ),
        }
    )



@router.post(
    "/run/{run_id}",
    response_model=APIResponse[dict],
    status_code=202,
    summary="Trigger LLM extraction + cluster summarization",
)
def run_llm_pipeline(
    run_id: int,
    background_tasks: BackgroundTasks,
    extract_limit: int | None = Query(
        200,
        description=(
            "Max incidents for per-summary extraction. "
            "200 = ~25 min dev mode. Set to 0 to skip extraction, "
            "null to run all (~8-13 hrs)."
        ),
    ),
    db: Session = Depends(get_db),
) -> APIResponse[dict]:
    """
    Prerequisites: run must be 'completed' (Phase 5 done).
    Returns immediately. Poll /api/v1/pipeline/{run_id}/status for progress.

    Timing estimates:
      extract_limit=0    → ~11 min  (cluster summaries only)
      extract_limit=200  → ~35 min  (recommended for dev)
      extract_limit=None → 8–13 hrs (full production run)
    """
    run = db.query(AnalysisRun).filter(AnalysisRun.id == run_id).first()
    if not run:
        raise HTTPException(status_code=404, detail=f"Run {run_id} not found.")

    allowed = {"completed", "llm_complete", "failed"}
    if run.status not in allowed:
        raise HTTPException(
            status_code=409,
            detail=(
                f"Run must be in {allowed} status to run LLM pipeline. "
                f"Current: '{run.status}'"
            ),
        )

    # Verify Ollama is up before accepting the job
    


    actual_limit = None if extract_limit == 0 and extract_limit is not None else extract_limit

    background_tasks.add_task(
        _orchestrator.run_llm_pipeline,
        run_id,
        actual_limit,
    )
    logger.info(
        f"LLM pipeline queued for run {run_id} "
        f"(extract_limit={extract_limit})"
    )

    return APIResponse(
        message="LLM pipeline started.",
        data={
            "run_id": run_id,
            "extract_limit": extract_limit,
            "estimated_minutes": (
                11 if extract_limit == 0
                else 35 if extract_limit == 200
                else "8–13 hours"
            ),
            "poll_url": f"/api/v1/pipeline/{run_id}/status",
        },
    )


@router.get(
    "/clusters",
    response_model=APIResponse[list],
    summary="All cluster summaries generated by LLM",
)
def list_cluster_summaries(
    db: Session = Depends(get_db),
) -> APIResponse[list]:
    """
    Returns all clusters that have been summarized.
    Ordered by incident_count descending — largest patterns first.
    """
    clusters = (
        db.query(Cluster)
        .filter(
            Cluster.cluster_label != -1,
            Cluster.root_cause_summary.isnot(None),
        )
        .order_by(Cluster.incident_count.desc())
        .all()
    )

    if not clusters:
        raise HTTPException(
            status_code=404,
            detail="No cluster summaries found. Run the LLM pipeline first.",
        )

    def _parse(raw: str | None) -> list:
        if not raw:
            return []
        try:
            return json.loads(raw)
        except Exception:
            return []

    return APIResponse(
        data=[
            {
                "cluster_label": c.cluster_label,
                "incident_count": c.incident_count,
                "year_range": f"{c.year_range_start}–{c.year_range_end}",
                "dominant_severity": c.dominant_severity,
                "avg_fatality_rate": c.avg_fatality_rate,
                "top_operators": _parse(c.top_operators),
                "top_aircraft_types": _parse(c.top_aircraft_types),
                "root_cause_summary": c.root_cause_summary,
                "key_contributing_factors": _parse(c.key_contributing_factors),
                "recommendations": c.recommendations,
                "summarized_at": (
                    c.summarized_at.isoformat() if c.summarized_at else None
                ),
            }
            for c in clusters
        ]
    )


@router.get(
    "/clusters/{cluster_label}",
    response_model=APIResponse[dict],
    summary="Full LLM summary for a specific cluster",
)
def get_cluster_summary(
    cluster_label: int,
    db: Session = Depends(get_db),
) -> APIResponse[dict]:
    cluster = (
        db.query(Cluster)
        .filter(Cluster.cluster_label == cluster_label)
        .first()
    )
    if not cluster:
        raise HTTPException(
            status_code=404,
            detail=f"Cluster {cluster_label} not found.",
        )
    if not cluster.root_cause_summary:
        raise HTTPException(
            status_code=404,
            detail=(
                f"Cluster {cluster_label} has not been summarized yet. "
                "Run the LLM pipeline first."
            ),
        )

    def _parse(raw: str | None) -> list:
        try:
            return json.loads(raw) if raw else []
        except Exception:
            return []

    return APIResponse(
        data={
            "cluster_label": cluster.cluster_label,
            "incident_count": cluster.incident_count,
            "year_range_start": cluster.year_range_start,
            "year_range_end": cluster.year_range_end,
            "dominant_severity": cluster.dominant_severity,
            "avg_fatality_rate": cluster.avg_fatality_rate,
            "avg_fatalities": cluster.avg_fatalities,
            "top_operators": _parse(cluster.top_operators),
            "top_aircraft_types": _parse(cluster.top_aircraft_types),
            "root_cause_summary": cluster.root_cause_summary,
            "key_contributing_factors": _parse(cluster.key_contributing_factors),
            "recommendations": cluster.recommendations,
            "summarized_at": (
                cluster.summarized_at.isoformat()
                if cluster.summarized_at else None
            ),
        }
    )


@router.get(
    "/extractions/stats",
    response_model=APIResponse[dict],
    summary="Per-incident extraction coverage statistics",
)
def get_extraction_stats(db: Session = Depends(get_db)) -> APIResponse[dict]:
    """Shows how many incidents have been through the structured extraction."""
    total = db.query(func.count(Incident.id)).scalar() or 0
    extracted = (
        db.query(func.count(Incident.id))
        .filter(Incident.extracted_cause_category.isnot(None))
        .scalar()
        or 0
    )

    cause_rows = (
        db.query(Incident.extracted_cause_category, func.count(Incident.id))
        .filter(Incident.extracted_cause_category.isnot(None))
        .group_by(Incident.extracted_cause_category)
        .all()
    )
    phase_rows = (
        db.query(Incident.extracted_phase_of_flight, func.count(Incident.id))
        .filter(Incident.extracted_phase_of_flight.isnot(None))
        .group_by(Incident.extracted_phase_of_flight)
        .all()
    )

    return APIResponse(
        data={
            "total_incidents": total,
            "extracted_count": extracted,
            "pending_count": total - extracted,
            "coverage_pct": round(extracted / total * 100, 1) if total else 0.0,
            "cause_distribution": dict(cause_rows),
            "phase_distribution": dict(phase_rows),
        }
    )
